#!/bin/bash
# vim: set ft=sh

set -e

#
# A little environment validation
#
if [ -z "$UAA_THEIRS" ]; then
  echo "must specify \$UAA_THEIRS path to local uaa-release repository jobs folder." >&2
  echo "example: export UAA_THEIRS='path/to/uaa-release/jobs/uaa'"
  echo "example: export UAA_THEIRS='path/to/uaa-release/jobs/uaa_postgres'"
  exit 1
fi

UAA_OURS=./jobs/uaa

# shellcheck disable=SC2045
echo "Sync the contents of uaa/templates."
for file in $(ls "$UAA_OURS/templates")
do
  file_name=$(echo "$file" | cut -d '/' -f 2)
  their_file="$UAA_THEIRS/templates/$file_name"
  our_file="$UAA_OURS/templates/$file_name"
  if [ -a "$their_file" ]
  then
    echo "comparing $their_file to $our_file"
    vimdiff "$their_file" "$our_file"
    echo ""
  fi
done

echo "Sync the spec file"
vimdiff $UAA_THEIRS/spec $UAA_OURS/spec
